on:
  push:
    branches:
      - 'main'

name: Publish package
jobs:
  trigger:
    name: Build Runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Decode pub credentials base64
        run: echo "PUB_CREDENTIALS=$(echo $ENCODED | base64 -d)" >> $GITHUB_ENV
        env:
          ENCODED: ${{ secrets.PUB_CREDENTIALS }}

      - name: Publish
        uses: sakebook/actions-flutter-pub-publisher@v1.4.0
        with:
          credential: ${{ env.PUB_CREDENTIALS }}
          flutter_package: false
          skip_test: true
          dry_run: true
